### ISSUE TITLE
python 2.7.5 tox problem: No module named _testcapi (CentOS 7)

### ISSUE THREAD

**Issue by seamang** [linkcheck/linkchecker#21] opened 2017-02-02 12:38 UTC
Trying to run tox and getting:

```
ImportError while importing test module '/home/graham/github/linkchecker-1/tests/checker/test_noproxy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/checker/test_noproxy.py:21: in <module>
    from test.test_support import EnvironmentVarGuard
/usr/lib64/python2.7/test/test_support.py:22: in <module>
    import _testcapi
E   ImportError: No module named _testcapi
```

This is CentOs 7, python 2.7.5. All searching does is tell me other CentOS 7 users have the same problem but no solution. Any suggestions?

**Comment by anarcat** [comment] 2017-02-02 14:36
this looks like something for @mgedmin  :)

**Comment by mgedmin** [comment] 2017-02-02 15:50
I'm afraid I've never used CentOS.  All I can say is that your Python appears to be broken.  :/

Can you do this experiment: `/usr/bin/python2.7 -c 'import _testcapi; print _testcapi.__file__` and report what you see?

**Comment by seamang** [comment] 2017-02-02 16:50
`/usr/bin/python2.7 -c 'import _testcapi; print _testcapi.__file__'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named _testcapi`

**Comment by mgedmin** [comment] 2017-02-02 17:24
Ok, so the bug is not in virtualenv failing to copy the _testcapi module, the bug is in CentOS python packages neglecting to ship it, while shipping a file (/usr/lib64/python2.7/test/test_support) that requires it.

Can you file a CentOS bug?

Meanwhile, to unblock you, can you install a non-broken Python 2.7 version from [EPEL](https://fedoraproject.org/wiki/EPEL), or with [pyenv](https://github.com/yyuu/pyenv), or from some other source?

**Comment by mgedmin** [comment] 2017-02-02 17:32
@anarcat we could implement a workaround for this (e.g. copy & paste the [EnvironmentVarGuard](https://docs.python.org/2/library/test.html?highlight=environmentvarguard#test.test_support.EnvironmentVarGuard) class into our test suite, or write a replacement, which would be like 10 lines of code.

**Comment by anarcat** [comment] 2017-02-02 18:40
i'd rather not add kludges to fix distribution bugs that are not our responsibility. we have enough kludging as it is, no?

i would just make sure this is filed in CentOS and close this issue, personally, but i won't object to a PR fixing this either, of course.

**Comment by seamang** [comment] 2017-02-03 10:29
Reported: https://bugs.centos.org/view.php?id=12774

On install of 2.7.13 from source tox now runs though some tests still failing:

21 failed, 186 passed, 15 skipped, 2 xfailed, 1 pytest-warnings in 54.00 seconds

**Comment by mgedmin** [comment] 2017-02-03 12:09
Try `tox -r` to tell tox to re-create the virtualenvs.

I would also like to see what those 6 test failures look like.

**Comment by seamang** [comment] 2017-02-03 14:05
tox -r fails with multiple errors. Key one seems to be:

`File "/usr/lib64/python2.7/hashlib.py", line 98, in __get_openssl_constructor f(usedforsecurity=False)
TypeError: openssl_md5() takes no keyword arguments`

I may just have messed up my real environment (I install python 2.7.13 with 'make altinstall' but had prefix set to /usr/bin instead of /urs/local/bin.

**Comment by seamang** [comment] 2017-02-03 14:06
`=================================== FAILURES ===================================
______________________________ TestHttp.test_html ______________________________

self = <tests.checker.test_http.TestHttp testMethod=test_html>

    def test_html (self):
        confargs = dict(recursionlevel=1)
>       self.file_test("http.html", confargs=confargs)

tests/checker/test_http.py:34: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/checker/__init__.py:199: in file_test
    self.fail_unicode(msg)
tests/checker/__init__.py:205: in fail_unicode
    self.fail(msg)
E   AssertionError: http://localhost:45998/tests/checker/data/http.html
E   --- 
E   
E   +++ 
E   
E   @@ -1,6 +1,7 @@
E   
E    url http://localhost:45998/tests/checker/data/http.html
E    cache key http://localhost:45998/tests/checker/data/http.html
E    real url http://localhost:45998/tests/checker/data/http.html
E   +info Ignoring proxy setting `http://10.112.110.254:8080/'.
E    valid
E    url clsid:12345-67890
E    cache key clsid:12345-67890
E   @@ -10,6 +11,7 @@
E   
E    url 
E    cache key http://localhost:45998/tests/checker/data/http.html
E    real url http://localhost:45998/tests/checker/data/http.html
E   +info Ignoring proxy setting `http://10.112.110.254:8080/'.
E    valid
E    url dns://www.example.org
E    cache key dns://www.example.org
E   @@ -28,34 +30,41 @@
E   
E    cache key http://localhost:45998/?d=directory&p=page
E    real url http://localhost:45998/?d=directory&p=page
E    name should not be cached
E   +info Ignoring proxy setting `http://10.112.110.254:8080/'.
E    valid
E    url /?d=directory&p=page1
E    cache key http://localhost:45998/?d=directory&p=page1
E    real url http://localhost:45998/?d=directory&p=page1
E    name should not be cached
E   +info Ignoring proxy setting `http://10.112.110.254:8080/'.
E    valid
E    url /?q=?
E    cache key http://localhost:45998/?q=%C3%BC
E    real url http://localhost:45998/?q=%C3%BC
E    name html entities
E   +info Ignoring proxy setting `http://10.112.110.254:8080/'.
E    valid
E    url file.html
E    cache key http://localhost:45998/tests/checker/data/file.html
E    real url http://localhost:45998/tests/checker/data/file.html
E   +info Ignoring proxy setting `http://10.112.110.254:8080/'.
E    valid
E    url file.css
E    cache key http://localhost:45998/tests/checker/data/file.css
E    real url http://localhost:45998/tests/checker/data/file.css
E   +info Ignoring proxy setting `http://10.112.110.254:8080/'.
E    valid
E    url file.asc
E    cache key http://localhost:45998/tests/checker/data/file.asc
E    real url http://localhost:45998/tests/checker/data/file.asc
E    name CSS urls
E   +info Ignoring proxy setting `http://10.112.110.254:8080/'.
E    valid
E    url file.txt
E    cache key http://localhost:45998/tests/checker/data/file.txt
E    real url http://localhost:45998/tests/checker/data/file.txt
E    name CSS urls
E   +info Ignoring proxy setting `http://10.112.110.254:8080/'.
E    valid
E    url http://example.org/foo/ #a=1,2,3
E    cache key http://example.org/foo/%20
_____________________________ TestHttp.test_status _____________________________

self = <tests.checker.test_http.TestHttp testMethod=test_status>

    def test_status(self):
        for status in sorted(self.handler.responses.keys()):
>           self._test_status(status)

tests/checker/test_http.py:43: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/checker/test_http.py:59: in _test_status
    self.direct(url, resultlines, recursionlevel=0)
tests/checker/__init__.py:228: in direct
    self.fail_unicode(unicode(os.linesep).join(l))
tests/checker/__init__.py:205: in fail_unicode
    self.fail(msg)
E   AssertionError: Differences found testing http://localhost:35048/status/100
E   @@ -1,4 +1,5 @@
E    url http://localhost:35048/status/100
E    cache key http://localhost:35048/status/100
E    real url http://localhost:35048/status/100
E   +info Ignoring proxy setting `http://10.112.110.254:8080/'.
E    error
____________________________ TestHttpMisc.test_html ____________________________

self = <tests.checker.test_http_misc.TestHttpMisc testMethod=test_html>

    def test_html (self):
>       self.swf_test()

tests/checker/test_http_misc.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/checker/test_http_misc.py:44: in swf_test
    self.direct(url, resultlines, recursionlevel=1)
tests/checker/__init__.py:228: in direct
    self.fail_unicode(unicode(os.linesep).join(l))
tests/checker/__init__.py:205: in fail_unicode
    self.fail(msg)
E   AssertionError: Differences found testing http://localhost:41822/tests/checker/data/test.swf
E   @@ -1,6 +1,7 @@
E    url http://localhost:41822/tests/checker/data/test.swf
E    cache key http://localhost:41822/tests/checker/data/test.swf
E    real url http://localhost:41822/tests/checker/data/test.swf
E   +info Ignoring proxy setting `http://10.112.110.254:8080/'.
E    valid
E    url http://www.example.org/
E    cache key http://www.example.org/
________________________ TestHttpRedirect.test_redirect ________________________

self = <tests.checker.test_http_redirect.TestHttpRedirect testMethod=test_redirect>

    def test_redirect (self):
>       self.redirect1()

tests/checker/test_http_redirect.py:30: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/checker/test_http_redirect.py:47: in redirect1
    self.direct(url, resultlines, recursionlevel=0)
tests/checker/__init__.py:228: in direct
    self.fail_unicode(unicode(os.linesep).join(l))
tests/checker/__init__.py:205: in fail_unicode
    self.fail(msg)
E   AssertionError: Differences found testing http://localhost:38129/redirect1
E   @@ -1,5 +1,6 @@
E    url http://localhost:38129/redirect1
E    cache key http://localhost:38129/redirect1
E    real url http://localhost:38129/newurl1
E   +info Ignoring proxy setting `http://10.112.110.254:8080/'.
E    info Redirected to `http://localhost:38129/newurl1'.
E    error
___________________________ TestHttpRobots.test_html ___________________________

self = <tests.checker.test_http_robots.TestHttpRobots testMethod=test_html>

    def test_html (self):
>       self.robots_txt_test()

tests/checker/test_http_robots.py:26: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/checker/test_http_robots.py:37: in robots_txt_test
    self.direct(url, resultlines, recursionlevel=5)
tests/checker/__init__.py:228: in direct
    self.fail_unicode(unicode(os.linesep).join(l))
tests/checker/__init__.py:205: in fail_unicode
    self.fail(msg)
E   AssertionError: Differences found testing http://localhost:44115/robots.txt
E   @@ -1,4 +1,5 @@
E    url http://localhost:44115/robots.txt
E    cache key http://localhost:44115/robots.txt
E    real url http://localhost:44115/robots.txt
E   +info Ignoring proxy setting `http://10.112.110.254:8080/'.
E    valid
_______________________ TestHttpsRedirect.test_redirect ________________________

self = <tests.checker.test_https_redirect.TestHttpsRedirect testMethod=test_redirect>

    def test_redirect (self):
        url = u"http://localhost:%d/redirect1" % self.port
        nurl = url
        #rurl = u"https://localhost:%d/newurl1" % self.port
        resultlines = [
            u"url %s" % url,
            u"cache key %s" % nurl,
            u"real url %s" % url,
            # XXX the redirect fails because this is not an SSL server
            #u"info Redirected to `%s'." % rurl.replace('http:', 'https:'),
            #u"valid",
            #u"url %s" % rurl,
            #u"cache key %s" % rurl,
            #u"real url %s" % rurl,
            u"error",
        ]
>       self.direct(url, resultlines, recursionlevel=0)

tests/checker/test_https_redirect.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/checker/__init__.py:228: in direct
    self.fail_unicode(unicode(os.linesep).join(l))
tests/checker/__init__.py:205: in fail_unicode
    self.fail(msg)
E   AssertionError: Differences found testing http://localhost:37719/redirect1
E   @@ -1,4 +1,5 @@
E    url http://localhost:37719/redirect1
E    cache key http://localhost:37719/redirect1
E    real url http://localhost:37719/redirect1
E   +info Ignoring proxy setting `http://10.112.110.254:8080/'.
E    error
============================ pytest-warning summary ============================
WC1 None --result-log is deprecated and scheduled for removal in pytest 4.0
 6 failed, 202 passed, 15 skipped, 2 xfailed, 1 pytest-warnings in 56.07 seconds 
make:`

**Comment by mgedmin** [comment] 2017-02-03 14:39
Thank you!

I wonder why tox doesn't strip off `http_proxy` from the environment.  From my reading of the [tox documentation](http://tox.readthedocs.io/en/latest/config.html#confval-passenv=SPACE-SEPARATED-GLOBNAMES) it should be doing so.

**Comment by seamang** [comment] 2017-02-03 15:11
1. Those tests were run using 'make test', not tox. 
2. I've reverted to the stock centos python 2.7.5 but my system is now too broken to continue with this. Will come back to it later.

**Comment by mgedmin** [comment] 2017-02-06 11:52
I'm going to close this since it appears the problems were not caused by any bugs in linkchecker itself.

**Closed by mgedmin** 2017-02-06 11:52 UTC
