### ISSUE TITLE
SSLError: SSLV3_ALERT_HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by richb-hanover** [linkcheck/linkchecker#35] opened 2017-02-12 18:40 UTC
Using LinkChecker 9.4 (Commit bf66006) on OSX 10.10.5 with Python 2.7.11: 

I get the following error when attempting to scan https://bufferbloat.net. What other information can I collect? Thanks!

```
bash-3.2$ ./linkchecker --version
INFO linkcheck.cmdline 2017-02-12 13:32:06,614 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 9.4 released xx.xx.xxxx
Copyright (C) 2000-2014 Bastian Kleineidam

bash-3.2$ ./linkchecker https://bufferbloat.net
INFO linkcheck.cmdline 2017-02-12 13:32:19,431 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 9.4              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/wummel/linkchecker/issues
Support this project at http://wummel.github.io/linkchecker/donations.html

Start checking at 2017-02-12 13:32:19-004

URL        `https://bufferbloat.net'
Real URL   https://bufferbloat.net
Check time 0.577 seconds
Result     Error: SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)

Statistics:
Downloaded: 0B.
Content types: 0 image, 0 text, 0 video, 0 audio, 0 application, 0 mail and 1 other.
URL lengths: min=23, max=23, avg=23.

That's it. 1 link in 1 URL checked. 0 warnings found. 1 error found.
Stopped checking at 2017-02-12 13:32:20-004 (0.60 seconds)
bash-3.2$
```

**Comment by mgedmin** [comment] 2017-02-13 13:09
I don't use OSX myself, so this is all hearsay, but I hear that Apple is basically never updating the OpenSSL library shipped with Mac OS X, which leaves the users with old versions that do not support modern TLS protocol versions or cipher suites.  I think you may be suffering from this: http://stackoverflow.com/a/36897862/110151.

**Comment by richb-hanover** [comment] 2017-02-13 15:02
OK, a bit of progress, but not success. See my question below about making sure Python is using the right version...

Here's what I know (recorded for posterity). I did have an old OpenSSL on my OSX 10.10.5 box, with Python 2.7.11: 
```
bash-3.2$ openssl version
OpenSSL 0.9.8zg 14 July 2015
```
I used `brew update; brew install openssl --force` to unlink the previous version from /opt and install 1.0.2k:
```
bash-3.2$ openssl version
OpenSSL 1.0.2k  26 Jan 2017
```
But... brew output some advisory messages while installing:
```
bash-3.2$ brew install openssl --force
Warning: openssl: this formula has no --force option so it will be ignored!
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2k.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring openssl-1.0.2k.yosemite.bottle.tar.gz
==> Using the sandbox
==> Caveats
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2k: 1,696 files, 12M
```

I did add /usr/local/opt/openssl/bin to my $PATH. I also see the other advisories "for compilers..." regarding LDFLAGS, CPPFLAGS, PKG_CONFIG_PATH.

**My question:** Do any of these affect the Python install? Do I need to do anything else?

Thanks again!

**Comment by mgedmin** [comment] 2017-02-13 15:14
Again, I've no experience with Mac OS X.  On Linux upgrading OpenSSL would affect Python if and only if the new OpenSSL version used the same SONAME.  I don't know if Macs OS X even has the concept of SONAME.

You may find better help in other forums, e.g. StackOverflow, or the [support channels for the Requests library](http://docs.python-requests.org/en/master/community/support/) that LinkChecker uses.

**Comment by richb-hanover** [comment] 2017-02-13 15:17
A perfect response. I'll check over there. Thanks again!

**Comment by mgedmin** [comment] 2017-02-13 15:20
I'll close this, since it looks like a platform problem and not a bug in LinkChecker itself.

**Closed by mgedmin** 2017-02-13 15:20 UTC

**Comment by richb-hanover** [comment] 2017-02-25 04:13
For posterity, I found a solution. The following site https://stackoverflow.com/questions/41524217/requesting-data-from-a-website-isnt-working-loading-python3 suggested a re-install of `requests` followed by a re-make, like this:

```
pip install requests[security]
make localbuild
```
I am now successfully retrieving pages from my https site.
